### ISSUE TITLE
chassis::waitUntilFinished() potentially not written as intended?

### ISSUE THREAD

**Issue by iamthehazard** [purduesigbots/ARMS#111]
Perhaps this is intentional, but it seems to me that `chassis::waitUntilFinished()`, as currently written, likely doesn't do what it's "supposed" to. For example, consider the following code.
```cpp
case ANGULAR:
        while (fabs(odom::getHeading() - pid::angularTarget) > exit_error && !settled())
	        pros::delay(10);
        break;
```
This waits until _either_ `fabs(odom::getHeading() - pid::angularTarget) <= exit_error` or the robot is settled, and then breaks. Shouldn't it wait until _both_ of these conditions are satisfied?

**Comment by iamthehazard** [comment]
One possible use of the way `chassis::waitUntilFinished()` is currently written is that it can automatically break out of a motion if your robot gets stuck and its speed (almost) stops changing, but I doubt that this was intentional?

**Comment by AndrewLuGit** [comment]
That is intentional. What happens sometimes is that the robot will stop moving, but the linear error is still larger than the exit error, so in that case it will exit the loop as well. I do think it is not ideal for all cases, and perhaps letting the user choose the exit condition of the while loop (whether it waits for either condition or both) would help.
